config/routes.rb
Rails.application.routes.draw do
  get 'users/user_profile', to: 'users#user_profile'
  get 'users/user_rentals', to: 'users#user_rentals'

  devise_for :users
  root to: 'plushes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :plushes, only: [:new, :create, :index, :show, :destroy] do
    resources :rentals, only: [:new, :create]
  end
  resources :users, only: [:user_profile] do
    resources :plushes, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plush.rb
class Plush < ApplicationRecord
  AUTHORIZED_COLORS = %w[Green White Yellow Red Blue Grey Brown Black].sort
  AUTHORIZED_SIZES = %w[Small Medium Large]

  include PgSearch::Model

  belongs_to :owner, class_name: "User"
  has_many :rentals
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :tenant, class_name: "User"
  belongs_to :plush

  validates :date, presence: true

  default_scope { order(date: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :plushes, foreign_key: 'owner_id'
  has_many :rentals, foreign_key: 'tenant_id'
  # has_many :my_rentals, through: :plushes

  # validates :name, presence: true
  # validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  #after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/plushes_controller.rb
class PlushesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index

    @plushes = Plush.all
    if params[:query].present?
      # sql_query = "name @@ :query OR description @@ :query"
      # @plushes = Plush.where(sql_query, query: "%#{params[:query]}%")
      @plushes = Plush.search_by_name_and_description(params[:query])
    end
    if params[:color].present?
      @plushes = @plushes.where(color: params[:color])
    end
    if params[:size].present?
      @plushes = @plushes.where(size: params[:size])
    end

    @markers = @plushes.geocoded.map do |plush|
    {
      lat: plush.latitude,
      lng: plush.longitude,
      info_window: render_to_string(partial: "info_window", locals: { plush: plush })
    }
    end
  end


  def show
    @plush = Plush.find(params[:id])
    authorize @plush
    @rental = Rental.new
    @rentals = @plush.rentals
    @rentals_dates = @rentals.map do |rental|
      {
        from: rental.date,
        to:   rental.date
      }
    end
  end

  def new
    @plush = Plush.new
    authorize @plush
  end

  def create
  @plush = Plush.new(plush_params)
  authorize @plush
  @plush.owner_id = current_user.id
    if @plush.save
      redirect_to users_user_profile_path
    else
      render :new
    end
  end

  def destroy
    @plush = Plush.find(params[:id])
    authorize @plush
    if @plush.rentals.any?
      flash[:alert] = "Cette peluche est déjà louée, elle ne peut pas être supprimée"
    else
      @plush.destroy
    end
    redirect_to users_user_profile_path(@plush)
  end

  private

  def plush_params
    params.require(:plush).permit(:name, :description, :price, :photo, :owner, :address, :color, :size)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def create
    @rental = Rental.new(rental_params)
    @plush = Plush.find(params[:plush_id])
    @tenant = current_user
    authorize @rental
    @rental.save
    redirect_to plush_path(@plush), notice: "Peluche bien reservée"
  end

  private

  def rental_params
    params.require(:rental).permit(:date, :tenant_id, :plush_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def user_profile
    @user = current_user
    authorize @user
    @plushes = Plush.all
  end

  def user_rentals
    @user = current_user
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@300;500;800&family=Roboto+Slab:wght@300;400;500&family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <title>Plushbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>

  <%= render 'shared/flashes' %>


      <%= yield %>
    </div>
    <section> </section>
    <div class="footer_top"></div>
<footer>
      <div class="text-center">
        <p class="mb-0 py-2">© 2021 Plushes Bnb All rights reserved.</p>
      </div>
</footer>
</body>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/my_profile.html.erb
<h1>Profile</h1>
<p><%= current_user.email %></p>

app/views/plushes/_info_window.html.erb
<h2><%= plush.name %></h2>
<h2><%= plush.address %></h2>

app/views/plushes/index.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>
  <div class="carousel-inner">
    <div class="carousel-item active">
       <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://voyage-onirique.com/wp-content/uploads/2020/11/teddy-bears-cute-alone-in-forest-wallpaper.jpg);" alt="First slide">
          <h1>Welcome <strong>to</strong> Plushes Bnb</strong>!</h1>
          <p>Never leave without your plush!</p>
       </div>
      </div>
      <div class="carousel-item ">
        <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.istockphoto.com/photos/giraffe-soft-toy-and-plush-animal-doll-on-white-background-for-kids-picture-id1036215656?k=20&m=1036215656&s=612x612&w=0&h=uv3ypcvCvS2Zl2HqUc4QVmVQSV5LjCX7RW9DhlbjuAc=);" alt="Second slide">
          <h1>Welcome <strong>to</strong> Plushes Bnb</strong>!</h1>
          <p>Never leave without your plush!</p>
          </div>
        </div>
      <div class="carousel-item ">
        <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://ae01.alicdn.com/kf/HTB1Q.CKKFXXXXXpXXXXq6xXFXXXP/Vente-chaude-25pcs-lot-ours-Paddington-Kawaii-peluche-porte-cl-s-Jouet-Doll-meilleur-cadeau-pour.jpg_Q90.jpg_.webp);" alt="Second slide">
          <h1>Welcome <strong>to</strong> Plushes Bnb</strong>!</h1>
          <p>Never leave without your plush!</p>
          </div>
        </div>
   </div>
   <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
   </div>





<%# <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://voyage-onirique.com/wp-content/uploads/2020/11/teddy-bears-cute-alone-in-forest-wallpaper.jpg);">
  <div class="container">
    <h1>Welcome <strong>to</strong> Plushes Bnb</strong>!</h1>
    <p>Never leave without your plush!</p>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  <%# </div>
</div> %>




<div class="title-home">
    <h1>Meet our Plushes</h1>
</div>
<div class="container1">
<div class="search-home">
  <%= simple_form_for :query, method: :get,
                                  defaults: { wrapper_html: { class: "mr-3" },
                                              required: false },
                                  html: { class: 'd-flex my-2' } do |f| %>
        <%= f.input :query, label: false,
                            input_html: { name: 'query',
                                          placeholder: "Find a plush",
                                          value: params.dig(:query) } %>
        <%= f.input :color, label:         false,
                                  collection:    Plush.distinct.pluck(:color),
                                  include_blank: 'Color',
                                  selected:      params[:color],
                                  input_html:    { name: :color } %>
        <%= f.input :size, label:         false,
                               collection:    Plush.distinct.pluck(:size),
                               include_blank: 'Size',
                               selected:      params[:size],
                               input_html:    { name: :size } %>
        <%= f.submit "Chercher", class: "button-home" %>
        <% end %>
    <p>
    <% case @plushes.count
      when 0 %> No plush match your search
    <% when 1 %> <%= @plushes.count %> plush matches your search :
    <% else %> <%= @plushes.count %> plushes match your search :
    <% end %>
    </p>
</div>
</div>

<div class="grid-map">
  <div class="text">
<div class="container-home">
</div>

<div class="container">
  <div class="cards-grid">
    <% @plushes.each do |plush| %>
      <%= link_to plush_path(plush) do %>
        <div class="card" >
          <% if plush.photo.attached? %>
            <%= cl_image_tag plush.photo.key, class:"card-img-top" %>
          <% else %>
            <img class="card-img-top" src="https://cdn-icons-png.flaticon.com/512/620/620744.png">
          <% end %>
          <div class="card-title">
            <h4 class="card-title"><%= plush.name %></h4>
          </div>
          <div class="card-body">
            <p class="card-text"><%= plush.description %></p>
            <h6><i class="fas fa-euro-sign"></i><span><%= plush.price %></span></h6>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
</div>
<div id="map"
     style="width: 100%; height: 800px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/plushes/new.html.erb
<div class="padding_top">
</div>

<div class="container_registration">
<h2>New Plush</h2>

<% if policy(Plush).create? %>
  <%= simple_form_for(@plush) do |f| %>
  <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :size, collection: Plush::AUTHORIZED_SIZES %>
    <%= f.input :color, collection: Plush::AUTHORIZED_COLORS %>
    <%= f.input :address %>
    <%= f.input :photo, as: :file %>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
<% end %>
<%= link_to 'Back', users_user_profile_path %>

</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="sticky">
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to "/plushes", class: "navbar-brand" do %>
    <img src="https://cdn-icons-png.flaticon.com/512/620/620744.png" alt="">
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/plushes", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <img class="far fa-user" class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="" />
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", users_user_profile_path, class: "dropdown-item" %>
            <%= link_to "My rentals", users_user_rentals_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Sign in", "/users/sign_up", class: "nav-link" %>
          </li>
        <li class="nav-item active">
          <%= link_to "Login", new_user_session_path, class: "nav-link"  %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</div>
</nav>

app/views/users/user_profile.html.erb
<div class="grid-map1">
 <div class="card-user">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" >
                    <div class="user_info">
                      <h1><%= current_user.name %></h1>
                      <h6>Email: <%= current_user.email %></h6>
                    </div>

<%= link_to 'Add a plush', new_plush_path, class: "button" %>
 </div>


<div class="container">


<div class="wrapper">
    <% current_user.plushes.each do |owner_plush| %>
      <div class="card">
      <%= link_to plush_path(owner_plush) do %>
        <% if owner_plush.photo.attached? %>
          <%= cl_image_tag owner_plush.photo.key, class: "card-img-top"%>
        <% else %>
          <p>No photo</p>
        <% end %>
    <% end %>
        <div class="card-title">
          <p><%= owner_plush.name %></p>
        </div>

        <div class="bouton">
              <%= link_to "", plush_path(owner_plush),
              method: :delete,
              data: { confirm: "Are you sure?" },
              class: "fas fa-trash" %>
        </div>
      </div>
    <% end %>

</div>
</div>

</div>

app/views/users/user_rentals.html.erb
<div class="container">
<div class="barre">
<h5>My plushes rentals</h5>
</div>
  <div class="cards-grid">
  <% current_user.plushes.each do |plush| %>
          <% plush.rentals.each do |rental| %>
        <div class="card" >
          <% if plush.photo.attached? %>
          <p><%= rental.plush.name %></p>
            <%= cl_image_tag plush.photo.key, class:"card-img-top" %>
          <% else %>
            <img class="card-img-top" src="https://cdn-icons-png.flaticon.com/512/620/620744.png">
          <% end %>
          <div class="card-title">
          <h2><%= rental.plush.name %></h2>
          </div>
          <div class="card-body">
            <p class="card-text"><%= plush.description %></p>
            <p class="card-text"> Booked by : <%= rental.tenant.name %></p>
            <h3 class="card-title">Booking date: <%= rental.date.strftime('%d/%m/%Y') %> </h3>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
</div>





<div class="container">
<div class="barre">
<h5>My plushes bookings</h5>
</div>
  <div class="cards-grid">
  <% current_user.rentals.each do |rental| %>
        <div class="card" >
          <% if rental.plush.photo.attached? %>
          <p><%= rental.plush.name %></p>
            <%= cl_image_tag rental.plush.photo.key, class:"card-img-top" %>
          <% else %>
            <img class="card-img-top" src="https://cdn-icons-png.flaticon.com/512/620/620744.png">
          <% end %>
          <div class="card-title">
          <h2><%= rental.plush.name %></h2>
          </div>
          <div class="card-body">
            <p class="card-text"><%= rental.plush.description %></p>
            <p class="card-text"> Owner : <%= rental.plush.owner.name %></p>
            <h3 class="card-title">Booking date: <%= rental.date.strftime('%d/%m/%Y') %> </h3>
          </div>
        </div>
      <% end %>
  </div>
  </div>
</div>